#!/usr/bin/env php
<?php

use ShoppinPal\YapepCommon\HealthCheck\Batch\LastRunChecker;

$vendorPaths = [
    __DIR__ . '/../../autoload.php',
    __DIR__ . '/../vendor/autoload.php',
    __DIR__ . '/vendor/autoload.php'
];

foreach ($vendorPaths as $file) {
    if (file_exists($file)) {
        $foundAutoloaderPath = $file;

        break;
    }
}

if (!isset($foundAutoloaderPath)) {
    fwrite(
        STDERR,
        'You need to set up the project dependencies using Composer:' . PHP_EOL . PHP_EOL
            . 'composer install' . PHP_EOL . PHP_EOL
            . 'You can learn all about Composer on https://getcomposer.org/.' . PHP_EOL
    );

    exit(1);
}

require $foundAutoloaderPath;

unset($file, $vendorPaths, $foundAutoloaderPath);

(new LastRunChecker())->run();
